version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/chat-app'

  web:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - app

